# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLGo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MLGo
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'CYLTabBarController' #https://github.com/ChenYilong/CYLTabBarController
  pod 'LCNavigationController' # https://github.com/iTofu/LCNavigationController
  
end
